#!/usr/bin/env bash

set -e

mix deps.get
MIX_ENV=prod mix release --env prod
mkdir -p playground
cp _build/prod/rel/simple_api/releases/$1/simple_api.tar.gz ./playground
cd ./playground
tar -zxvf simple_api.tar.gz
rm simple_api.tar.gz
